apiVersion: v1
kind: ConfigMap
metadata:
  name: member-cluster-id
data:
  id: aks-member-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: python
          image: shaomq/fleet-app
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: MEMBER_CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: member-cluster-id
                key: id
          resources:
            requests:
              cpu: "0.2"
              memory: "400M"
            limits:
              cpu: "0.2"
              memory: "400M"
          volumeMounts:
            - mountPath: /etc/podinfo
              name: podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "name"
                fieldRef:
                  fieldPath: metadata.name
              - path: "namespace"
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080