apiVersion: v1
kind: Pod
metadata:
  annotations:
    aks.component/sig: aks-privatecluster
    checksum/config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
  creationTimestamp: "2023-09-10T15:08:41Z"
  generateName: ambassador-7b8b7c75c4-
  labels:
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ambassador
    app.kubernetes.io/part-of: ambassador
    kubernetes.azure.com/mdsd-tag: mdsd.ambassadorgateway
    pod-template-hash: 7b8b7c75c4
    product: aes
  name: ambassador-7b8b7c75c4-vf7zt
  namespace: ambassador
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ambassador-7b8b7c75c4
    uid: 2a90d4d0-9bff-4787-b4fe-1dd2f9c47593
  resourceVersion: "5190"
  uid: 194a4541-4968-4e3e-8648-0bc3156b5dae
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - agentpool1
  containers:
  - env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: AMBASSADOR_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: AMBASSADOR_FAST_RECONFIGURE
      value: "true"
    - name: AKS_BIN_VERSION_BUILDTIME
      value: "2023-09-10T15:07:55Z"
    image: mcr.microsoft.com/aks/hcp/datawire/ambassador:1.12.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /ambassador/v0/check_alive
        port: admin
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    name: ambassador
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
    - containerPort: 8877
      name: admin
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ambassador/v0/check_ready
        port: admin
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 300m
        memory: 300Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/ambassador-pod-info
      name: ambassador-pod-info
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-z9rc2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool1-20826189-vmss000003
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 8888
  serviceAccount: ccp-api-gateway
  serviceAccountName: ccp-api-gateway
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: agentpool
    operator: Equal
    value: infra
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
    name: ambassador-pod-info
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - name: kube-api-access-z9rc2
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-10T15:08:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-10T15:09:18Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-10T15:09:18Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-10T15:08:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f70247affac5a2cba27310d453a2cb66afc8bd75b95ef2fe7ec2b3884b8fe854
    image: mcr.microsoft.com/aks/hcp/datawire/ambassador:1.12.4
    imageID: mcr.microsoft.com/aks/hcp/datawire/ambassador@sha256:4ac207287fc6e47929a7e35d347c07af1c9469af21116148b87c9b36f5fbaac7
    lastState: {}
    name: ambassador
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-09-10T15:08:46Z"
  hostIP: 10.224.0.7
  phase: Running
  podIP: 172.24.0.17
  podIPs:
  - ip: 172.24.0.17
  qosClass: Burstable
  startTime: "2023-09-10T15:08:41Z"
