FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod a+x ./kubectl
ADD ./.kube /.kube
ADD ./crp.yaml /crp.yaml
ADD ./deployment-1.yaml /deployment-1.yaml
ADD ./deployment-2.yaml /deployment-2.yaml
ADD ./run.sh /run.sh
RUN chmod a+x /run.sh

CMD /run.sh