apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: demo
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - name: demo
        image: shaomq/demo:v8
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: [
                "/bin/sh", "-c", "sleep 60"
              ]
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          successThreshold: 20
          periodSeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    run: demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: demo