apiVersion: v1
kind: Pod
metadata:
  name: spn
  namespace: default
spec:
  containers:
  - image: shaomq/env
    imagePullPolicy: Always
    name: bash
    resources:
      requests:
        memory: 1G
        cpu: 0.1
  - env:
    - name: SUBSCRIPTION_ID
      value: 8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8
    - name: RESOURCE_GROUP_NAME
      value: minshaebld58588564
    - name: MANAGED_CLUSTER_NAME
      value: minshamember9900
    - name: CONTROL_PLANE_ID
      value: 62eb36b80287d3000132f3eb
    image: mcr.microsoft.com/aks/ccp/msi-adapter:master.220529.1
    imagePullPolicy: IfNotPresent
    name: msi-adapter
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  volumes:
  - emptyDir: {}
    name: provider-token
