//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.1, generator: @autorest/go@4.0.0-preview.43)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package v20220702preview

const (
	moduleName    = "v20220702preview"
	moduleVersion = "v0.0.1"
)

// CreatedByType - The type of identity that created the resource.
type CreatedByType string

const (
	CreatedByTypeApplication     CreatedByType = "Application"
	CreatedByTypeKey             CreatedByType = "Key"
	CreatedByTypeManagedIdentity CreatedByType = "ManagedIdentity"
	CreatedByTypeUser            CreatedByType = "User"
)

// PossibleCreatedByTypeValues returns the possible values for the CreatedByType const type.
func PossibleCreatedByTypeValues() []CreatedByType {
	return []CreatedByType{
		CreatedByTypeApplication,
		CreatedByTypeKey,
		CreatedByTypeManagedIdentity,
		CreatedByTypeUser,
	}
}

// FleetMemberProvisioningState - The provisioning state of the last accepted operation.
type FleetMemberProvisioningState string

const (
	FleetMemberProvisioningStateCanceled  FleetMemberProvisioningState = "Canceled"
	FleetMemberProvisioningStateFailed    FleetMemberProvisioningState = "Failed"
	FleetMemberProvisioningStateJoining   FleetMemberProvisioningState = "Joining"
	FleetMemberProvisioningStateLeaving   FleetMemberProvisioningState = "Leaving"
	FleetMemberProvisioningStateSucceeded FleetMemberProvisioningState = "Succeeded"
	FleetMemberProvisioningStateUpdating  FleetMemberProvisioningState = "Updating"
)

// PossibleFleetMemberProvisioningStateValues returns the possible values for the FleetMemberProvisioningState const type.
func PossibleFleetMemberProvisioningStateValues() []FleetMemberProvisioningState {
	return []FleetMemberProvisioningState{
		FleetMemberProvisioningStateCanceled,
		FleetMemberProvisioningStateFailed,
		FleetMemberProvisioningStateJoining,
		FleetMemberProvisioningStateLeaving,
		FleetMemberProvisioningStateSucceeded,
		FleetMemberProvisioningStateUpdating,
	}
}

// FleetMembershipProvisioningState - The provisioning state of the last accepted operation.
type FleetMembershipProvisioningState string

const (
	FleetMembershipProvisioningStateCanceled  FleetMembershipProvisioningState = "Canceled"
	FleetMembershipProvisioningStateFailed    FleetMembershipProvisioningState = "Failed"
	FleetMembershipProvisioningStateJoining   FleetMembershipProvisioningState = "Joining"
	FleetMembershipProvisioningStateLeaving   FleetMembershipProvisioningState = "Leaving"
	FleetMembershipProvisioningStateSucceeded FleetMembershipProvisioningState = "Succeeded"
	FleetMembershipProvisioningStateUpdating  FleetMembershipProvisioningState = "Updating"
)

// PossibleFleetMembershipProvisioningStateValues returns the possible values for the FleetMembershipProvisioningState const type.
func PossibleFleetMembershipProvisioningStateValues() []FleetMembershipProvisioningState {
	return []FleetMembershipProvisioningState{
		FleetMembershipProvisioningStateCanceled,
		FleetMembershipProvisioningStateFailed,
		FleetMembershipProvisioningStateJoining,
		FleetMembershipProvisioningStateLeaving,
		FleetMembershipProvisioningStateSucceeded,
		FleetMembershipProvisioningStateUpdating,
	}
}

// FleetProvisioningState - The provisioning state of the last accepted operation.
type FleetProvisioningState string

const (
	FleetProvisioningStateCanceled  FleetProvisioningState = "Canceled"
	FleetProvisioningStateCreating  FleetProvisioningState = "Creating"
	FleetProvisioningStateDeleting  FleetProvisioningState = "Deleting"
	FleetProvisioningStateFailed    FleetProvisioningState = "Failed"
	FleetProvisioningStateSucceeded FleetProvisioningState = "Succeeded"
	FleetProvisioningStateUpdating  FleetProvisioningState = "Updating"
)

// PossibleFleetProvisioningStateValues returns the possible values for the FleetProvisioningState const type.
func PossibleFleetProvisioningStateValues() []FleetProvisioningState {
	return []FleetProvisioningState{
		FleetProvisioningStateCanceled,
		FleetProvisioningStateCreating,
		FleetProvisioningStateDeleting,
		FleetProvisioningStateFailed,
		FleetProvisioningStateSucceeded,
		FleetProvisioningStateUpdating,
	}
}

type MemberClusterResourceProvider string

const (
	MemberClusterResourceProviderMicrosoftContainerService MemberClusterResourceProvider = "Microsoft.ContainerService"
)

// PossibleMemberClusterResourceProviderValues returns the possible values for the MemberClusterResourceProvider const type.
func PossibleMemberClusterResourceProviderValues() []MemberClusterResourceProvider {
	return []MemberClusterResourceProvider{
		MemberClusterResourceProviderMicrosoftContainerService,
	}
}

type MemberClusterResourceType string

const (
	MemberClusterResourceTypeManagedClusters MemberClusterResourceType = "managedClusters"
)

// PossibleMemberClusterResourceTypeValues returns the possible values for the MemberClusterResourceType const type.
func PossibleMemberClusterResourceTypeValues() []MemberClusterResourceType {
	return []MemberClusterResourceType{
		MemberClusterResourceTypeManagedClusters,
	}
}
