//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.1, generator: @autorest/go@4.0.0-preview.43)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package v20220702preview

import "time"

// AzureEntityResource - The resource model definition for an Azure Resource Manager resource with an etag.
type AzureEntityResource struct {
	// Resource Etag.
	Etag *string `json:"etag,omitempty"`

	// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string `json:"id,omitempty"`

	// The name of the resource
	Name *string `json:"name,omitempty"`

	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`

	// READ-ONLY; Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData `json:"systemData,omitempty" azure:"ro"`
}

// ErrorAdditionalInfo - The resource management error additional info.
type ErrorAdditionalInfo struct {
	// The additional info.
	Info interface{} `json:"info,omitempty"`

	// The additional info type.
	Type *string `json:"type,omitempty"`
}

// ErrorDetail - The error detail.
type ErrorDetail struct {
	// The error additional info.
	AdditionalInfo []*ErrorAdditionalInfo `json:"additionalInfo,omitempty"`

	// The error code.
	Code *string `json:"code,omitempty"`

	// The error details.
	Details []*ErrorDetail `json:"details,omitempty"`

	// The error message.
	Message *string `json:"message,omitempty"`

	// The error target.
	Target *string `json:"target,omitempty"`
}

// ErrorResponse - Common error response for all Azure Resource Manager APIs to return error details for failed operations.
// (This also follows the OData error response format.).
type ErrorResponse struct {
	// The error object.
	Error *ErrorDetail `json:"error,omitempty"`
}

// Fleet - The Fleet resource which contains multiple Kubernetes clusters as its members.
type Fleet struct {
	// REQUIRED; The geo-location where the resource lives
	Location *string `json:"location,omitempty"`

	// Resource Etag.
	Etag *string `json:"etag,omitempty"`

	// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string `json:"id,omitempty"`

	// The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties of a Fleet.
	Properties *FleetProperties `json:"properties,omitempty"`

	// Resource tags.
	Tags map[string]*string `json:"tags,omitempty"`

	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`

	// READ-ONLY; Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData `json:"systemData,omitempty" azure:"ro"`
}

// FleetCredentialResult - The credential result response.
type FleetCredentialResult struct {
	// The name of the credential.
	Name *string `json:"name,omitempty"`

	// Base64-encoded Kubernetes configuration file.
	Value []byte `json:"value,omitempty"`
}

// FleetCredentialResults - The list credential result response.
type FleetCredentialResults struct {
	// Base64-encoded Kubernetes configuration file.
	Kubeconfigs []*FleetCredentialResult `json:"kubeconfigs,omitempty"`
}

// FleetHubProfile - The FleetHubProfile configures the fleet hub.
type FleetHubProfile struct {
	// DNS prefix used to create the FQDN for the Fleet hub.
	DNSPrefix *string `json:"dnsPrefix,omitempty"`

	// The FQDN of the Fleet hub.
	Fqdn *string `json:"fqdn,omitempty"`

	// The Kubernetes version of the Fleet hub.
	KubernetesVersion *string `json:"kubernetesVersion,omitempty"`
}

// FleetListResult - The response from the List Fleets operation.
type FleetListResult struct {
	// The URL to get the next page of Fleets.
	NextLink *string `json:"nextLink,omitempty"`

	// The list of Fleets.
	Value []*Fleet `json:"value,omitempty"`
}

// FleetMember - A member of the Fleet. It contains a reference to an existing Kubernetes cluster on Azure.
type FleetMember struct {
	// Resource Etag.
	Etag *string `json:"etag,omitempty"`

	// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string `json:"id,omitempty"`

	// The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties of a Fleet member.
	Properties *FleetMemberProperties `json:"properties,omitempty"`

	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`

	// READ-ONLY; Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData `json:"systemData,omitempty" azure:"ro"`
}

// FleetMemberProperties - Properties of a Fleet member.
type FleetMemberProperties struct {
	// The ARM resource id of the cluster that joins the Fleet. Must be a valid Azure resource id. e.g.:
	// '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{clusterName}'.
	ClusterResourceID *string `json:"clusterResourceId,omitempty"`

	// The provisioning state of the last accepted operation.
	ProvisioningState *FleetMemberProvisioningState `json:"provisioningState,omitempty"`
}

// FleetMembersClientBeginCreateOrUpdateOptions contains the optional parameters for the FleetMembersClient.BeginCreateOrUpdate
// method.
type FleetMembersClientBeginCreateOrUpdateOptions struct {
	// Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting
	// concurrent changes.
	IfMatch *string
	// Set to '*' to allow a new resource to be created and prevent updating an existing resource. Other values will result in
	// a 412 Pre-condition Failed response.
	IfNoneMatch *string
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// FleetMembersClientBeginDeleteOptions contains the optional parameters for the FleetMembersClient.BeginDelete method.
type FleetMembersClientBeginDeleteOptions struct {
	// Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting
	// concurrent changes.
	IfMatch *string
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// FleetMembersClientGetOptions contains the optional parameters for the FleetMembersClient.Get method.
type FleetMembersClientGetOptions struct {
	// placeholder for future optional parameters
}

// FleetMembersClientListByFleetOptions contains the optional parameters for the FleetMembersClient.ListByFleet method.
type FleetMembersClientListByFleetOptions struct {
	// placeholder for future optional parameters
}

// FleetMembersListResult - The response from the List FleetMembers operation.
type FleetMembersListResult struct {
	// The URL to get the next page of Fleet members.
	NextLink *string `json:"nextLink,omitempty"`

	// The list of members in a given Fleet.
	Value []*FleetMember `json:"value,omitempty"`
}

// FleetMembershipExtension - The FleetMembershipExtension is applied on Kubernetes cluster resources that are part of a Fleet.
// It contains a reference to the Fleet resource id.
type FleetMembershipExtension struct {
	// Resource Etag.
	Etag *string `json:"etag,omitempty"`

	// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string `json:"id,omitempty"`

	// The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties of the FleetMembership extension resource.
	Properties *FleetMembershipExtensionProperties `json:"properties,omitempty"`

	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`

	// READ-ONLY; Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData `json:"systemData,omitempty" azure:"ro"`
}

// FleetMembershipExtensionProperties - The properties of a fleet membership extension.
type FleetMembershipExtensionProperties struct {
	// REQUIRED; CertificateAuthorityData contains PEM-encoded certificate authority certificates to trust the hub cluster's TLS.
	// The data is passed as a base64 encoded string.
	CertificateAuthorityData *string `json:"certificateAuthorityData,omitempty"`

	// REQUIRED; The fleet hub url the member will connect to.
	FleetHubURL *string `json:"fleetHubUrl,omitempty"`

	// REQUIRED; The resource id of the fleet this member has joined. Must be a valid fleet resource id. e.g.:
	// '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/fleets/{fleetName}'.
	FleetResourceID *string `json:"fleetResourceId,omitempty"`

	// REQUIRED; The member's name in the fleet
	MemberName *string `json:"memberName,omitempty"`

	// REQUIRED; The tenant id of the user
	TenantID *string `json:"tenantId,omitempty"`

	// The provisioning state of the last accepted operation.
	ProvisioningState *FleetMembershipProvisioningState `json:"provisioningState,omitempty"`
}

// FleetMembershipsClientBeginCreateOrUpdateOptions contains the optional parameters for the FleetMembershipsClient.BeginCreateOrUpdate
// method.
type FleetMembershipsClientBeginCreateOrUpdateOptions struct {
	// Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting
	// concurrent changes.
	IfMatch *string
	// Set to '*' to allow a new resource to be created and prevent updating an existing resource. Other values will result in
	// a 412 Pre-condition Failed response.
	IfNoneMatch *string
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// FleetMembershipsClientBeginDeleteOptions contains the optional parameters for the FleetMembershipsClient.BeginDelete method.
type FleetMembershipsClientBeginDeleteOptions struct {
	// Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting
	// concurrent changes.
	IfMatch *string
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// FleetMembershipsClientGetOptions contains the optional parameters for the FleetMembershipsClient.Get method.
type FleetMembershipsClientGetOptions struct {
	// placeholder for future optional parameters
}

// FleetPatch - Properties of a Fleet that can be patched.
type FleetPatch struct {
	// Resource tags.
	Tags map[string]*string `json:"tags,omitempty"`
}

// FleetProperties - Properties of a Fleet.
type FleetProperties struct {
	// The FleetHubProfile configures the Fleet's hub.
	HubProfile *FleetHubProfile `json:"hubProfile,omitempty"`

	// The provisioning state of the last accepted operation.
	ProvisioningState *FleetProvisioningState `json:"provisioningState,omitempty"`
}

// FleetsClientBeginCreateOrUpdateOptions contains the optional parameters for the FleetsClient.BeginCreateOrUpdate method.
type FleetsClientBeginCreateOrUpdateOptions struct {
	// Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting
	// concurrent changes.
	IfMatch *string
	// Set to '*' to allow a new resource to be created and prevent updating an existing resource. Other values will result in
	// a 412 Pre-condition Failed response.
	IfNoneMatch *string
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// FleetsClientBeginDeleteOptions contains the optional parameters for the FleetsClient.BeginDelete method.
type FleetsClientBeginDeleteOptions struct {
	// Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting
	// concurrent changes.
	IfMatch *string
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// FleetsClientGetOptions contains the optional parameters for the FleetsClient.Get method.
type FleetsClientGetOptions struct {
	// placeholder for future optional parameters
}

// FleetsClientListByResourceGroupOptions contains the optional parameters for the FleetsClient.ListByResourceGroup method.
type FleetsClientListByResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// FleetsClientListCredentialsOptions contains the optional parameters for the FleetsClient.ListCredentials method.
type FleetsClientListCredentialsOptions struct {
	// placeholder for future optional parameters
}

// FleetsClientListOptions contains the optional parameters for the FleetsClient.List method.
type FleetsClientListOptions struct {
	// placeholder for future optional parameters
}

// FleetsClientUpdateOptions contains the optional parameters for the FleetsClient.Update method.
type FleetsClientUpdateOptions struct {
	// Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting
	// concurrent changes.
	IfMatch *string
}

// Resource - Common fields that are returned in the response for all Azure Resource Manager resources
type Resource struct {
	// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string `json:"id,omitempty"`

	// The name of the resource
	Name *string `json:"name,omitempty"`

	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`

	// READ-ONLY; Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData `json:"systemData,omitempty" azure:"ro"`
}

// SystemData - Metadata pertaining to creation and last modification of the resource.
type SystemData struct {
	// The timestamp of resource creation (UTC).
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// The identity that created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// The type of identity that created the resource.
	CreatedByType *CreatedByType `json:"createdByType,omitempty"`

	// The timestamp of resource last modification (UTC)
	LastModifiedAt *time.Time `json:"lastModifiedAt,omitempty"`

	// The identity that last modified the resource.
	LastModifiedBy *string `json:"lastModifiedBy,omitempty"`

	// The type of identity that last modified the resource.
	LastModifiedByType *CreatedByType `json:"lastModifiedByType,omitempty"`
}

// TrackedResource - The resource model definition for an Azure Resource Manager tracked top level resource which has 'tags'
// and a 'location'
type TrackedResource struct {
	// REQUIRED; The geo-location where the resource lives
	Location *string `json:"location,omitempty"`

	// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string `json:"id,omitempty"`

	// The name of the resource
	Name *string `json:"name,omitempty"`

	// Resource tags.
	Tags map[string]*string `json:"tags,omitempty"`

	// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`

	// READ-ONLY; Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData `json:"systemData,omitempty" azure:"ro"`
}
