//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.1, generator: @autorest/go@4.0.0-preview.43)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package v20220702preview

// FleetMembersClientCreateOrUpdateResponse contains the response from method FleetMembersClient.CreateOrUpdate.
type FleetMembersClientCreateOrUpdateResponse struct {
	FleetMember
}

// FleetMembersClientDeleteResponse contains the response from method FleetMembersClient.Delete.
type FleetMembersClientDeleteResponse struct {
	// placeholder for future response values
}

// FleetMembersClientGetResponse contains the response from method FleetMembersClient.Get.
type FleetMembersClientGetResponse struct {
	FleetMember
}

// FleetMembersClientListByFleetResponse contains the response from method FleetMembersClient.ListByFleet.
type FleetMembersClientListByFleetResponse struct {
	FleetMembersListResult
}

// FleetMembershipsClientCreateOrUpdateResponse contains the response from method FleetMembershipsClient.CreateOrUpdate.
type FleetMembershipsClientCreateOrUpdateResponse struct {
	FleetMembershipExtension
}

// FleetMembershipsClientDeleteResponse contains the response from method FleetMembershipsClient.Delete.
type FleetMembershipsClientDeleteResponse struct {
	// placeholder for future response values
}

// FleetMembershipsClientGetResponse contains the response from method FleetMembershipsClient.Get.
type FleetMembershipsClientGetResponse struct {
	FleetMembershipExtension
}

// FleetsClientCreateOrUpdateResponse contains the response from method FleetsClient.CreateOrUpdate.
type FleetsClientCreateOrUpdateResponse struct {
	Fleet
}

// FleetsClientDeleteResponse contains the response from method FleetsClient.Delete.
type FleetsClientDeleteResponse struct {
	// placeholder for future response values
}

// FleetsClientGetResponse contains the response from method FleetsClient.Get.
type FleetsClientGetResponse struct {
	Fleet
}

// FleetsClientListByResourceGroupResponse contains the response from method FleetsClient.ListByResourceGroup.
type FleetsClientListByResourceGroupResponse struct {
	FleetListResult
}

// FleetsClientListCredentialsResponse contains the response from method FleetsClient.ListCredentials.
type FleetsClientListCredentialsResponse struct {
	FleetCredentialResults
}

// FleetsClientListResponse contains the response from method FleetsClient.List.
type FleetsClientListResponse struct {
	FleetListResult
}

// FleetsClientUpdateResponse contains the response from method FleetsClient.Update.
type FleetsClientUpdateResponse struct {
	Fleet
}
